### ISSUE TITLE
Trojan in window releases?

### ISSUE THREAD

**Issue by dawm** [smford/tplink-hs1x-cli#1]
1.3.4 Window releases --> Detected: Trojan:Win32/Wacatac.B!ml

**Comment by smford** [comment]
@dawm which antivirus software are you using?

That windows release was compiled on osx and eset isn't detecting it for me.  I had a quick google and apparently there can be false positives with that particular trojan.

If you can provide some extra info about your setup I'll try figure out what is happening.

**Comment by smford** [comment]
Closing because I think this is a false positive in the virus scanner, I am not finding this when using ESET virus scanners on various versions on OSX.

If you are still concerned about the binary, just use another installation method which downloads and compiles the code on your platform.

Below is an extract from a [post](https://answers.microsoft.com/en-us/protect/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a) which describes what to do about the false positive:
```
... if you continue to be alerted to its presence, that would be a false positive.  You can prove that, by downloading the Microsoft Safety Scanner, and scan your PC with that. If it does not detect Wacatac, you can be sure, that you are seeing a false positive.

https://docs.microsoft.com/en-us/windows/security/threat-protection/intelligence/safety-scanner-download

You can eliminate that false positive, by deleting Wacatac from Defender's Protection History.

The following explains how to accomplish that in W10. I suspect that this applies to W11 also.

Open File Explorer, and on the View Tab, check the box for "Hidden Items".

Then navigate through this path.

C:\ProgramData\Microsoft\Windows Defender\Scans\History\Service

Open the Service folder. If you find a folder in it, named Detection History, then W11 is the same as W10 in this regard.  Delete Detection History, and the false notification regarding Wacatac will cease.

Not to worry, Windows rebuilds Detection History when it is needed next.
```

Example discussions about the false positive results:
- https://answers.microsoft.com/en-us/protect/forum/all/what-to-do-about-trojanwin32wacatacbml-false/d884df80-2dba-46c9-bd8b-4e2f93c9dd3f
- https://answers.microsoft.com/en-us/protect/forum/all/how-can-i-know-if-wacatacbml-is-a-false-positive/33107e01-d390-4579-aa94-625a3402d26a
